### ISSUE TITLE
LSP-rust-analyzer broken on NixOs

### ISSUE THREAD

**Issue by makemake-kbo** [sublimelsp/LSP-rust-analyzer#126]
LSP-rust-analyzer is appears to be broken on NixOS.

I set up my rust environment in a nix-shell, with all the necessary tools including rust-analyzer. However, when launching sublime, I am met with this error:
![image](https://github.com/sublimelsp/LSP-rust-analyzer/assets/55022497/57988893-b8a9-475a-947d-c14acdc6148d)

I'm attributing this to LSP-rust-analyzer downloading its own binary instead of using the one in PATH. Is there any way for this behavior to be changed?

**Comment by predragnikolic** [comment]
When you installed LSP-rust-analyzer, were there some installation errors in the Sublime Text console(ctrl+`) ?
Can you remove and install LSP-rust-analyzer again and can check the console for errors?
 
> I'm attributing this to LSP-rust-analyzer downloading its own binary instead of using the one in PATH. Is there any way for this behavior to be changed?

In LSP-rust-analyzer.sublime-settings, you can override the start command:
```jsonc
{
	"command": [
		"${storage_path}/LSP-rust-analyzer/rust-analyzer"  // change the path to your local rust-analyzer
	],
}
```

But I would not recommend overriding the command
because there is no guarantee that this LSP-rust-analyzer
version is compatible with rust-analyzer you have locally, so you may run into a different issues somet

**Comment by rchl** [comment]
The first error is from EasyClangComplete. Maybe try removing/disabling it (LSP-clang should work better anyway) and then checking if that solves the problem.

**Comment by makemake-kbo** [comment]
heres the logs when starting sublime with it disabled:
```python
Unable to start subprocess for rust-analyzer
Traceback (most recent call last):
  File "/home/makemake/.config/sublime-text/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 273, in start_async
    transport = create_transport(transport_config, transport_cwd, session)
  File "/home/makemake/.config/sublime-text/Installed Packages/LSP.sublime-package/plugin/core/transports.py", line 265, in create_transport
    process = start_subprocess()
  File "/home/makemake/.config/sublime-text/Installed Packages/LSP.sublime-package/plugin/core/transports.py", line 253, in start_subprocess
    return _start_subprocess(config.command, stdin, stdout, subprocess.PIPE, startupinfo, config.env, cwd)
  File "/home/makemake/.config/sublime-text/Installed Packages/LSP.sublime-package/plugin/core/transports.py", line 339, in _start_subprocess
    cwd=cwd)
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1452, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/home/makemake/.cache/sublime-text/Package Storage/LSP-rust-analyzer/rust-analyzer'

Unable to start subprocess for rust-analyzer
Traceback (most recent call last):
  File "/home/makemake/.config/sublime-text/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 273, in start_async
    transport = create_transport(transport_config, transport_cwd, session)
  File "/home/makemake/.config/sublime-text/Installed Packages/LSP.sublime-package/plugin/core/transports.py", line 265, in create_transport
    process = start_subprocess()
  File "/home/makemake/.config/sublime-text/Installed Packages/LSP.sublime-package/plugin/core/transports.py", line 253, in start_subprocess
    return _start_subprocess(config.command, stdin, stdout, subprocess.PIPE, startupinfo, config.env, cwd)
  File "/home/makemake/.config/sublime-text/Installed Packages/LSP.sublime-package/plugin/core/transports.py", line 339, in _start_subprocess
    cwd=cwd)
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1452, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/home/makemake/.cache/sublime-text/Package Storage/LSP-rust-analyzer/rust-analyzer'
```

**Comment by predragnikolic** [comment]
@makemake-kbo 

Can you verify that this binary file exist `/home/makemake/.cache/sublime-text/Package Storage/LSP-rust-analyzer/rust-analyzer` ?

The file must exist if LSP-rust-analyzer installs successfully.

**Comment by makemake-kbo** [comment]
@predragnikolic 
looks like it is
```bash
file /home/makemake/.cache/sublime-text/Package\ Storage/LSP-rust-analyzer/rust-analyzer 
/home/makemake/.cache/sublime-text/Package Storage/LSP-rust-analyzer/rust-analyzer: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=4cb9801d931e886ce8110ee6af8892ce8c77f2c7, with debug_info, not stripped

ls -la /home/makemake/.cache/sublime-text/Package\ Storage/LSP-rust-analyzer/
total 43376
drwxr-xr-x 2 makemake users     4096 Feb 26 12:48 .
drwxrwxr-x 7 makemake users     4096 Feb 26 12:48 ..
-rwxr--r-- 1 makemake users 44402448 Feb 26 12:48 rust-analyzer
-rw-r--r-- 1 makemake users       10 Feb 26 12:48 VERSION
```

**Comment by rchl** [comment]
maybe related to permissions (the `makemake` user is not the one used when starting from ST)?

**Comment by predragnikolic** [comment]
Maybe found the cause:

https://nixos.wiki/wiki/Packaging/Binaries

> Downloading and attempting to run a binary on NixOS will almost never work. This is due to hard-coded paths in the executable.

**Comment by predragnikolic** [comment]
Other editors faced the same issue in NixOS

https://discourse.nixos.org/t/nix-shell-and-rust-and-rust-analyzer/13940/2

I do not understand or know NixOS to suggest a solution to you.

**Comment by makemake-kbo** [comment]
Thank you all for the useful info! If i find a solution ill come back and post it.
