### ISSUE TITLE
Server can't work on windows

### ISSUE THREAD

**Issue by jingyuexing** [sublimelsp/LSP-rust-analyzer#58]
```
rust-analyzer: [ERROR rust_analyzer::reload] failed to switch workspaces: rust-analyzer failed to load workspace: "C:\\Users\\Jingyuexing\\.cargo\\bin" "--version" failed: Access denied。 (os error 5)
rust-analyzer: 

```

**Comment by Daggy1234** [comment]
Check your rust installation, seems to be an error using cargo

**Comment by jingyuexing** [comment]
```
Error handling request
Traceback (most recent call last):
  File "sublime_text_4100\Data\Installed Packages\LSP.sublime-package\plugin/core/sessions.py", line 1899, in on_payload
    handler(result, req_id)
  File "sublime_text_4100\Data\Installed Packages\LSP.sublime-package\plugin/core/sessions.py", line 1583, in m_workspace_semanticTokens_refresh
    selected_sheets.extend(self.window.selected_sheets_in_group(group))
AttributeError: 'Window' object has no attribute 'selected_sheets_in_group'
```

**Comment by jingyuexing** [comment]
each time the plugin is started, it will query a file path for version information
![image](https://user-images.githubusercontent.com/19589872/166644690-74cc4eef-d2b7-4522-9f7e-49dd7aead8c4.png)

why is the workspace in cargo????
