### ISSUE TITLE
rust-analyzer exited with status code 101

### ISSUE THREAD

**Issue by jingyuexing** [sublimelsp/LSP-rust-analyzer#66]
![image](https://user-images.githubusercontent.com/19589872/166659579-ebe309bd-a1da-4578-b779-d0171ac6ef48.png)

```
Error handling request
Traceback (most recent call last):
  File "sublime_text_4100\Data\Installed Packages\LSP.sublime-package\plugin/core/sessions.py", line 1899, in on_payload
    handler(result, req_id)
  File "sublime_text_4100\Data\Installed Packages\LSP.sublime-package\plugin/core/sessions.py", line 1583, in m_workspace_semanticTokens_refresh
    selected_sheets.extend(self.window.selected_sheets_in_group(group))
AttributeError: 'Window' object has no attribute 'selected_sheets_in_group'

scan: Code/Rust/hello_cargo/target/debug/incremental/hello_cargo-1hdyy0mm9k986/s-g9gp3hsaav-d632ad-working has been seen before, skipping (using content fingerprint) previous path: /H/Code/Rust/hello_cargo/target/debug/incremental/hello_cargo-2ipinpcb4sfc0/s-g9gp3hs8eg-1abb3mc-working fingerprint: 8837144147186434593
```

**Comment by rchl** [comment]
Are you still getting this issue?

**Comment by jingyuexing** [comment]
> Are you still getting this issue?

Because of the environment variables, I deleted some configuration environment variables of rust then is normal
